api:
  jwt:
    audience: Econect
    claim:
      login: loginUsuario
      name: nomeUsuario
      roles: permissoes
    expirationTimeInMinutes: 60
    issuer: ECI-API-Issuer
    notBeforeThePastInMinutes: 10
    subject: ECI-API-JTW-Token
  login:
    userLogin: econect
    userName: Econect ECI API
    userPasswd: 1234
    userRoles: 100,200,300,400

logging:
  level:
    br:
      econect:
        eci: INFO
    root: INFO

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

rsa:
  private-key: classpath:eci-private.pem
  public-key: classpath:eci-public.pem

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: false
  swagger-ui:
    path: /api-docs-ui.html
