server:
    servlet:
        context-path: /eci-classifmerc
    port: 0

spring:
    application:
        name: eci-classifmerc-service
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: B4nc0my5q1
        url: jdbc:mysql://localhost:3306/eci_classifmerc?createDatabaseIfNotExist=true
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
        show-sql: false

logging:
    level:
        br:
            econect:
                eci:
                    classifmerc: INFO
        root: INFO

