server:
    servlet:
        context-path: /eci-cliente
    port: 0

spring:
    application:
        name: eci-cliente-service
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: econect
        password: 12345
        url: jdbc:mysql://localhost:3306/eci_cliente?createDatabaseIfNotExist=true
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
        show-sql: false

logging:
    level:
        br:
            econect:
                eci:
                    cliente: INFO
        root: INFO

tempo-rotina-buscar-saldo-reservado-pendente: 5
tempo-invalidacao-credito-pendente: 15
